### ISSUE TITLE
[BUG] intersight_firmware_upgrade fails to handle destroys gracefully[Backend: INTERSIGHT-10298]

### ISSUE THREAD

**Issue by briamorr** [CiscoDevNet/terraform-provider-intersight#128]
**Describe the bug**
intersight_firmware_upgrade fails to handle destroys gracefully

**To Reproduce**
1. Run terraform apply on something similar to:
resource "intersight_firmware_upgrade" "sds-firmware-update" {
  upgrade_type =  "network_upgrade"
  network_share {
    map_type = "www"
    upgradeoption = "nw_upgrade_mount_only"
    http_server {
      location_link = "http://172.21.87.164/ucs-c220m5-huu-4.1.1d.iso"
    }
  }

  server {
    object_type = "compute.RackUnit"
    moid = data.intersight_compute_rack_unit.rack_unit1.results[0].moid
  }
}

2. It succeeds with starting the firmware update workflow
3. Cancel or otherwise terminate the firmware update and attempt to re-apply the plan
4. Observe it fails when terraform tries to destroy resources with an internal error
      + shared_scope           = (known after apply)
      - skip_estimate_impact   = false -> null
      ~ status                 = "FAILED" -> "NONE" # forces replacement
      ~ tags                   = [] -> (known after apply)
      ~ upgrade_impact         = [] -> (known after apply)
      ~ upgrade_status         = [
          - {
              - additional_properties = ""
              - class_id              = "mo.MoRef"
              - moid                  = "614213c97068612d32a77f40"
              - object_type           = "firmware.UpgradeStatus"
              - selector              = ""
            },
        ] -> (known after apply)
      ~ version_context        = [] -> (known after apply)
        # (3 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

intersight_firmware_upgrade.sds-firmware-update: Destroying... [id=614213c97068612d32a77f34]

Error: error occurred while deleting FirmwareUpgrade object: 500 Internal Server Error Response from endpoint: {"code":"InternalServerError","message":"Cannot execute the request due to an error. Retry later.","messageId":"barcelona_request_internal_error","messageParams":{},"traceId":"NB2a668f8894fdaf382af389ec6c87a3e9"}

**Expected behavior**
Handle firmware lifecycle gracefully

**Provider Version :** v1.0.15

**Comment by meghana-rajashekar** [comment]
#### Have raised an issue with intersight backend and will track it.
However, a quick workaround suggestion would be to remove the resource from tf state file and do an apply.
Since there is no identity constraint for this MO, it tries to create a new resource with the same config specified.

Command to remove the resource from state file:
**terraform state rm intersight_firmware_upgrade.sds-firmware-update**

**Comment by prmedipa** [comment]
1. Create a firmware.Upgrade using  terraform using the following payload:

```
resource "intersight_firmware_upgrade" "sds-firmware-update" {
  upgrade_type = "network_upgrade"
  network_share {
    map_type = "www"
    upgradeoption = "nw_upgrade_mount_only"
    http_server {
      location_link = var.location_link
    }
  }
  status = "NONE"
  server {
    object_type = "compute.RackUnit"
    moid = var.server_moid
  }
}
```
2. The above step successfully starts the upgrade. 

Now, terminate the workflow either by doing a patch with {"Action": "Cancel"} on workflow's moid or simply terminate the workflow from UI. You can get workflow Moid from Firmware.UpgradeStatus

3. Delete the firmware.Upgrade using terraform destroy works as expected.
``` Plan: 0 to add, 0 to change, 1 to destroy.

Do you really want to destroy all resources?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes

intersight_firmware_upgrade.sds-firmware-update: Destroying... [id=<MOID>]
intersight_firmware_upgrade.sds-firmware-update: Destruction complete after 1s```

4. Then do terraform apply again starts firmware.upgrade.
```
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

intersight_firmware_upgrade.sds-firmware-update: Creating...
intersight_firmware_upgrade.sds-firmware-update: Creation complete after 1s [id=<MOID>]
```

**Comment by prmedipa** [comment]
The destroy and reapply workflow operates as expected with the following steps:

``` # Define a firmware upgrade resource with network upgrade type
resource "intersight_firmware_upgrade" "sds-firmware-update" {
  upgrade_type = "network_upgrade"
  
  # Define the network share settings for the firmware upgrade
  network_share {
    map_type = "www"
    upgradeoption = "nw_upgrade_mount_only"
    
    # Specify the HTTP server location link
    http_server {
      location_link = var.location_link
    }
  }
  
  # Target a specific server using its moid
  server {
    object_type = "compute.RackUnit"
    moid = var.moid
  }
}

# Retrieve the firmware upgrade status using its moid
data "intersight_firmware_upgrade_status" "upgrade_status" {
  moid = intersight_firmware_upgrade.sds-firmware-update.upgrade_status.0.moid
}

# Define a resource for workflow cancellation of the firmware upgrade process
resource "intersight_workflow_workflow_info" "workflow" {
  action = "Cancel"
  name = "Upgrade Firmware"
}

# Apply the firmware upgrade resource
terraform apply -target="intersight_firmware_upgrade.sds-firmware-update"

# Import the workflow using its moid
terraform import intersight_workflow_workflow_info.workflow_workflow_info <workflow.moid>

# Apply the workflow cancellation
terraform apply -target="intersight_workflow_workflow_info.workflow"

# Destroy the firmware upgrade resource
terraform destroy -target="intersight_firmware_upgrade.sds-firmware-update"

# Reapply the firmware upgrade resource
terraform apply -target="intersight_firmware_upgrade.sds-firmware-update" ```

**Comment by the-akhil-nair** [comment]
Closing the issue as it is working as expected. If you face any issue please re-open the issue.
