### ISSUE TITLE
intersight_networkconfig_policy has inconsistent behavior with ipv6dns server arguments

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/terraform-provider-intersight#15]
When deploying the intersight_networkconfig_policy without IPv6 enabled, one would naturally **not** define the preferred/alternative IPv6 dns server arguments of:
- preferred_ipv6dns_server
- alternate_ipv6dns_server

However, when you deploy a policy following that behavior, such as the Terraform configuration below:

```
resource "intersight_networkconfig_policy" "GVE_RTP_DCV_DNS" {
    organization {
        moid = data.intersight_organization_organization.default.moid
    }
    
    description = "Terraform deployed"
    name = "GVE_RTP_DCV_DNS"
    preferred_ipv4dns_server = "8.8.8.8"
    alternate_ipv4dns_server = "8.8.4.4"
    enable_ipv6 = false
    enable_ipv6dns_from_dhcp = false
    enable_dynamic_dns = false

    profiles {
        object_type = "server.Profile"
        moid = intersight_server_profile.C240M4L.moid
    }
}

```

The initial 'terraform apply' is successful but subsequent 'terraform apply' attempts continue to make changes to the resource because those arguments are 'null' to Terraform but get stored in Intersight's model as '::'.  Example 'terraform plan' output shown here:

```
  # intersight_networkconfig_policy.GVE_RTP_DCV_DNS will be updated in-place
  ~ resource "intersight_networkconfig_policy" "GVE_RTP_DCV_DNS" {
      - alternate_ipv6dns_server = "::" -> null
        id                       = "5fc954a66275722d31b835e7"
        name                     = "GVE_RTP_DCV_DNS"
      - preferred_ipv6dns_server = "::" -> null
        # (14 unchanged attributes hidden)
    }

```

One workaround attempt which does NOT work is to initially (on greenfield deploy) define the arguments to equal '::' as shown below:

```
# Configure DNS ("Network Connectivity") policy
resource "intersight_networkconfig_policy" "GVE_RTP_DCV_DNS" {
    organization {
        moid = data.intersight_organization_organization.default.moid
    }
    
    description = "Terraform deployed"
    name = "GVE_RTP_DCV_DNS"
    preferred_ipv4dns_server = "8.8.8.8"
    alternate_ipv4dns_server = "8.8.4.4"
    preferred_ipv6dns_server = "::"
    alternate_ipv6dns_server = "::"
    enable_ipv6 = false
    enable_ipv6dns_from_dhcp = false
    enable_dynamic_dns = false

    profiles {
        object_type = "server.Profile"
        moid = intersight_server_profile.C240M4L.moid
    }
}

```

Attempting to have the IPv6 DNS server values set to '::' **even when enable_ipv6 is false** results in the following error from Intersight (truncated):

```
"messageId": "cannot_create_policy_with_ipv6_dns_ipv6_disable",
"messageParams": {},
"traceId": "NBedbdf9537bde87eb47f2f3b8ce8f466b"
```

Perhaps the behavior should be more like?
1. Terraform HCL configuration error when IPv6 arguments are provided when enable_ipv6 is false
2. Provider ignores IPv6 attributes returned from Intersight when enable_ipv6 is false

**Comment by gve-vse-tim** [comment]
Aanisha - this is tagged as help wanted... what sort of help do you need?

**Comment by code-lucidal58** [comment]
Closing this issue as progress will be tracked in #104. The later issues have suggestions and an ongoing discussion.
