### ISSUE TITLE
[BUG] Terraform documentation vs behavior for intersight_organization_organization loading resource_groups: more objects required

### ISSUE THREAD

**Issue by bwaldecker** [CiscoDevNet/terraform-provider-intersight#150]
**Describe the bug**
Following the example and documentation: https://registry.terraform.io/providers/CiscoDevNet/intersight/latest/docs/resources/organization_organization for the resource_group part:
  resource_groups = [{
    moid        = intersight_resource_group.resource1.id
    object_type = "resource.Group"
  }]

terraform provides back that required options are missing:
Error: Incorrect attribute value type
[...]
Inappropriate value for attribute "resource_groups": element 0: attributes "additional_properties", "class_id", and "selector" are required.

I tried as well to load the data with related reference, which works for all except for selector

   resource_groups = [{
     moid        = intersight_resource_group.resource_group1.id
     object_type = intersight_resource_group.resource_group1.object_type
     selector    = intersight_resource_group.resource_group1.selectors
     class_id    = intersight_resource_group.resource_group1.class_id
     additional_properties = intersight_resource_group.resource_group1.additional_properties
   }]

output from the terraform state part for  intersight_resource_group.resource_group1, which shows that selectors = [] is part of the 
resource "intersight_resource_group" "resource_group1" {
    [...]
    qualifier                  = "Allow-Selectors"
    selectors                  = []
    tags                       = []
    version_context            = []
}

**To Reproduce**
1. follow the example from the documention 
2. Run `terraform plan` 

**Expected behavior**

- correct documentation
- required parameters are part of the documentation e.g class_id and additional_properties are missing
- selectors are possible to use with the related reference like selector    = intersight_resource_group.resource_group1.selectors if 

**Screenshots and Terraform configurations**
Terraform version:
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/ciscodevnet/intersight v1.0.19

**Provider Version :**  v1.0.19

**Comment by meghana-rajashekar** [comment]
@bwaldecker The latest provider release (1.0.22) has proper examples in documentation.
#### Expected behavior
- [x] correct documentation  
     - Updated
- [x] required parameters are part of the documentation e.g class_id and additional_properties are missing  
     - Updated
- [x] selectors are possible to use with the related reference like selector = intersight_resource_group.resource_group1.selectors 
    - The ***selector*** for resource_groups.selector in organization.Organization resource is a ***string***. Whereas, ***resource_group1.selectors*** you're trying to assign is an ***array***.
