### ISSUE TITLE
[REQ] Provider - Insecure Option

### ISSUE THREAD

**Issue by bwaldecker** [CiscoDevNet/terraform-provider-intersight#155]
**Is your feature request related to a problem? Please describe.**
Based on the source code of the provider.go it is not possible to use the insecure option.
Backgroud: Intersight Appliances does not have an official certificate

**Describe the solution you'd like**
same solution as e.g. in the ACI provider.go implementation

**Describe alternatives you've considered**

**Additional context**
Actual terraform plan output with from an intersight appliance with self signed certificate:
 terraform plan
╷
│ Error: failed to get signature context: File '' does not contain PEM data
│
│   with provider["registry.terraform.io/ciscodevnet/intersight"],

**Comment by meghana-rajashekar** [comment]
#### @bwaldecker The error mentioned above is due to incorrect secretKey being fetched either from the file or from the string value passed in the config.
Please recheck the file name/file content.
Let me know if the issue still persists.
