### ISSUE TITLE
issue with Resource: intersight_hyperflex_cluster_profile example 

### ISSUE THREAD

**Issue by kzoran** [CiscoDevNet/terraform-provider-intersight#158]
there is an issue with usage example, it has an "=" sign that is throwing an error once executed  

```
resource "intersight_hyperflex_cluster_profile" "hyperflex_cluster_profile1" {
  storage_data_vlan = {
    name    = "hx-storage-data"
    vlan_id = 27
  }
```

It seems like storage_data_vlan is a hashmap, rather then attribute.

**Comment by meghana-rajashekar** [comment]
#### @kzoran Thanks for bringing this into notice.
It's taken care of in the latest release. (v1.0.22)
Please have a look: 
#### https://github.com/CiscoDevNet/terraform-provider-intersight/blob/master/website/docs/r/hyperflex_cluster_profile.html.markdown
