### ISSUE TITLE
Provider should also accept the content of a certificate (string) to authenticate

### ISSUE THREAD

**Issue by rtortori** [CiscoDevNet/terraform-provider-intersight#18]
At the moment the provider only supports a file (secretkeyfile).
This requires the file to actually exist when executing the plan, otherwise it will fail.
This is especially true when you don't have the certificate stored locally and you fetch it from a remote location, like Vault.

In a CI/CD environment, this means having two stages (two terraform runs): one that creates the file reading from Vault and another run that actually uses the file to authenticate to Intersight.

As an enhancement, we should also accept the content of a certificate as string rather than just a file.

**Comment by code-lucidal58** [comment]
If the secret key is given as a string, instead of the file path, the security breach will be very easy, since apikey and secretkey both will be available at one place i.e. in the single variable file.

**Comment by rtortori** [comment]
I understand the concern, however with the current authentication method on TF we are forcing the user to store the certificate locally on the machine that runs automation. 
Also, if a rotation mechanism is implemented, all users will have to re-upload the certificate on all machines, rather than just do it in a centralized safe place like Vault.

If the user is not responsible enough to secure the credentials, it will be unsafe anyway, even with the current method. Additionally, when implementing GitOps the user will also need to be sure the certificate is not uploaded on the repo during the commit. Implementing the string type for the certificate will allow the user to be more agnostic and handle authentication and automation with a single terraform run

**Comment by code-lucidal58** [comment]
Resolved in version 1.0.0
