### ISSUE TITLE
[BUG] Description for intersight_hyperflex_ext_iscsi_storage_policy is incorrect [Backend: INTERSIGHT-9034]

### ISSUE THREAD

**Issue by richwats** [CiscoDevNet/terraform-provider-intersight#183]
**Describe the bug**
Description for intersight_hyperflex_ext_iscsi_storage_policy is incorrect
"A policy specifying external storage connectivity information via Fabric attached FCoE storage."
should be..
"A policy specifying external storage connectivity information via Fabric attached iSCSI storage."

**Comment by the-akhil-nair** [comment]
Thanks for reaching out to us.

The description for intersight_hyperflex_ext_iscsi_storage_policy is changed now.
You can verify it in the latest intersight terraform provider documentation:

https://registry.terraform.io/providers/CiscoDevNet/intersight/latest/docs/resources/hyperflex_ext_iscsi_storage_policy
https://registry.terraform.io/providers/CiscoDevNet/intersight/latest/docs/resources/hyperflex_ext_iscsi_storage_policy
