### ISSUE TITLE
[REQ] HyperFlex Node Assignment via Node Profiles?

### ISSUE THREAD

**Issue by richwats** [CiscoDevNet/terraform-provider-intersight#187]
**Is your feature request related to a problem? Please describe.**
I would like to assign servers/nodes to an HX cluster profile.   To do this we need to create a "hyperflexNodeProfile" i.e. a per node profile that has the necessary IP addresses taken from the ranges in the associated HX node configuration policy. 

Currently we can create HX cluster profiles but need to use the GUI to manually assign the appropriate HX nodes to the cluster.

**Describe the solution you'd like**
I think a new resource such as "intersight_hyperflex_node" or "intersight_hyperflex_node_profile" would be required.

**Describe alternatives you've considered**
None, other than using the GUI to complete the configuration.

**Comment by richwats** [comment]
To clarify I'm looking to query and create "hyperflex.NodeProfile" objects

**Comment by richwats** [comment]
Apologies - looks like resource "intersight_hyperflex_node_profile" does exist but isn't grouped under hyperflex in the documentation.  Could we please add it there?

**Comment by meghana-rajashekar** [comment]
Fixed with latest provider release: v1.0.26
