### ISSUE TITLE
[BUG] Resource intersight_virtualization_virtual_network:  name must be lower case

### ISSUE THREAD

**Issue by richwats** [CiscoDevNet/terraform-provider-intersight#188]
**Describe the bug**
I've managed to create a resource with a capital letter name.  This caused a 500 server error.

**To Reproduce**
Use the intersight_virtualization_virtual_network to create a virtual network with a capital letter name.  

**Expected behavior**
Either the provider or Intersight API should either reject the capital name or convert to lower case.

**Provider Version :** v1.0.23

**Additional context**
Can provide MOIDs

**Comment by meghana-rajashekar** [comment]
@richwats Could you please provide more details on this issue?
What was the tf config used to create the resource ?

**Comment by richwats** [comment]
Hi Meghana,

My example is below, though I have fixed this to force lower cap names.   Previously I used this resource and just passed in the variable name as “LAB-29”.   This seemed to be passed to Intersight as capitals and triggered the 500 Internal Server Error response.  Doing the same thing but with lower case name worked fine.


data "intersight_virtualization_iwe_cluster" "this" {
  ## Cluster Details - NOT Profile Details
  cluster_name = var.cluster_name
}

resource "intersight_virtualization_virtual_network" "this" {
  name                    = lower(var.name)
  description             = var.description # default
  infra_network           = var.infra_network == null ? false : var.infra_network # default
  mtu                     = var.mtu == null ? 1500 : var.mtu #var.mtu # default
  network_type            = var.network_type == null ? "L2" : var.network_type # default
  trunk                   = var.trunk # default
  vlan                    = var.vlan_id
  vswitch                 = var.vswitch == null ? "vm" : var.vswitch # default
  wait_for_completion     = var.wait_for_completion # default

  dynamic "tags" {
    for_each = var.tags
    content {
      key   = tags.value.key
      value = tags.value.value
    }
  }

  registered_device {
    moid = data.intersight_virtualization_iwe_cluster.this.results[0].registered_device[0].moid
    object_type = "asset.DeviceRegistration"
  }

}

From: Meghana R ***@***.***>
Date: Wednesday, 23 March 2022 at 3:49 am
To: CiscoDevNet/terraform-provider-intersight ***@***.***>
Cc: Richard Watson (richwats) ***@***.***>, Mention ***@***.***>
Subject: Re: [CiscoDevNet/terraform-provider-intersight] [BUG] Resource intersight_virtualization_virtual_network: name must be lower case (Issue #188)

@richwats<https://github.com/richwats> Could you please provide more details on this issue?
What was the tf config used to create the resource ?
