### ISSUE TITLE
[BUG] intersight_ippool_pool unable to create IPv4 block

### ISSUE THREAD

**Issue by yannickcastano** [CiscoDevNet/terraform-provider-intersight#190]
**Describe the bug**
It is not possible to create Intersight IP pool with IPv4 block.
intersight_ippool_pool resources requires more parameters than the Intersight API can accept.
ip_v4_blocks int intersight_ippool_pool resources requires "to" and "size" parameters whereas the Intersight API can accept only one.
IP pool with embedded IPv4 block creation is failing because intersight_ippool_pool pushes to many parameters to the API

**To Reproduce**
1. Use the intersight_ippool_pool to create an IP pool containing an IP v4 block:
              resource "intersight_ippool_pool" "ippool_pool1" {
                organization {
                  object_type = "organization.Organization"
                  moid        = data.intersight_organization_organization.org_data.results.0.moid
                }
                name             = "${var.prefix}_ip_pool"
                description      = "${var.prefix} IP pool"
                assignment_order = "sequential"
                ip_v4_config {
                   object_type = "ippool.IpV4Config"
                   gateway     = "10.60.10.254"
                   netmask     = "255.255.255.0"
                   primary_dns = "8.8.8.8"
                }
                ip_v4_blocks = [
                  {
                   object_type = "ippool.IpV4Block"
                   class_id    = "ippool.IpV4Block"
                   from        = "10.60.10.210"
                   to          = "10.60.10.211"
                   size        = 2
                   additional_properties = ""
                  }
                ]
              }
-> Terraform plan is passing, Apply is failing.

2. Try to remove the "to" or "size" parameter from the IP block and now the Terraform plan is failing

**Expected behavior**
The intersight_ippool_pool should only require "to" or "size" parameter, not both of them.

**Provider Version** : v1.0.25

**Comment by meghana-rajashekar** [comment]
The issue is because of "[]" around the ip_v4_blocks - this adds a wrapping type list, so the type of the produced variable becomes list of lists. 
#### Terraform has understood this expression as a list of lists.
This can be solved by flattening the list.
#### Solution: You can specify the same config for ip_v4_blocks as below: 
(Hint - Use multiple declarations for multiple blocks as shown in below example)
``` hcl
resource "intersight_ippool_pool" "ippool_pool1" {
  organization {
    object_type = "organization.Organization"
    moid        = data.intersight_organization_organization.org_data.results.0.moid
  }
  name             = "${var.prefix}_ip_pool"
  description      = "${var.prefix} IP pool"
  assignment_order = "sequential"
  ip_v4_config {
    object_type = "ippool.IpV4Config"
    gateway     = "10.60.10.254"
    netmask     = "255.255.255.0"
    primary_dns = "8.8.8.8"
  }
  ip_v4_blocks {
    object_type = "ippool.IpV4Block"
    class_id    = "ippool.IpV4Block"
    from        = "10.60.10.210"
    to          = "10.60.10.211"
  }
  ip_v4_blocks {
    object_type = "ippool.IpV4Block"
    class_id    = "ippool.IpV4Block"
    from        = "10.60.10.214"
    to          = "10.60.10.216"
  }
}
```

The above configuration is tested on Provider Version : v1.0.25

**Comment by asmith432** [comment]
Hi. I'm getting this exact error on 1.0.44. Is there a workaround for this?
