### ISSUE TITLE
Windows x86 'Incompatible Provider Version'

### ISSUE THREAD

**Issue by trclemen** [CiscoDevNet/terraform-provider-intersight#225]
'Incompatible provider version' error when trying to use Intersight Terraform Provider with Win x86
'Provider registry.terraform.io/ciscodevnet/intersight v1.0.32 does not have a package available for your current platform, windows_386'

**Comment by scotttyso** [comment]
@trclemen I don't think 32bit is supported in any platform.  Is your operating system 32Bit or 64bit?

**Comment by scotttyso** [comment]
@vvb - Please close this as the answer has been provided and the last comment was two years ago
