### ISSUE TITLE
Need a datasource that returns a list of objects

### ISSUE THREAD

**Issue by techBeck03** [CiscoDevNet/terraform-provider-intersight#24]
### Problem Statement

There are certain scenarios where it makes sense to grab a list of objects.  Everything i've tried so far seems to randomly select a single item from a list when multiple are returned.  So in my opinion two things should happen as part of this issue:

### Proposed Enhancements
1. data sources intended to only provided a single return value should send an `Error` or `Warning` diag back to the user indicating that multiple results were found

2. There should be some method for searching for multiple items (`intersight_search_search_item` makes a lot of sense) where a list is returned as part of the data source

**Comment by code-lucidal58** [comment]
The first proposed enhancement is integrated and can be used in the latest version of the provider.
The second was under development. Targeted to be released in 1.0.2 release.

**Comment by code-lucidal58** [comment]
Closing this issue. Resolved in 1.0.2
