### ISSUE TITLE
[Feature-Request] API-Release 11765 - switch-control-policy.reserved

### ISSUE THREAD

**Issue by heitmanr** [CiscoDevNet/terraform-provider-intersight#241]
##### Description

I need to modify the reserved-VLAN-Range on an UCS-FI which is allowed in API-release 11765 according to Cisco SR 695508949.

[/api/v1/fabric/SwitchControlPolicies] (https://intersight.com/apidocs/apirefs/api/v1/fabric/SwitchControlPolicies/post/)

![image](https://github.com/CiscoDevNet/terraform-provider-intersight/assets/26636908/68d5a77f-a4af-4a97-b49b-e1b7899933f3)

##### Terraform-provider-intersight version

1.0.35

The top-level-description of the terraform-docs already contains a hint to "reserved VLAN range" but in the body no details appear.

https://registry.terraform.io/providers/CiscoDevNet/intersight/latest/docs/resources/fabric_switch_control_policy.

The .go-code lacks support of this parameter:
![image](https://github.com/CiscoDevNet/terraform-provider-intersight/assets/26636908/93565e02-2593-42e8-9703-9cdedb9c4b97)

##### Workaround

I'll expect, creating the Object using the Intersight-GUI and importing it as a datasource might us to use this parameter without breaking our deployment model.

**Comment by vvb** [comment]
@heitmanr Please try this with 1.0.36

**Comment by Ghufz** [comment]
This parameter named "reserved_vlan_start_id" can be configured using the latest intersight terraform provider v1.0.36

reference : https://github.com/CiscoDevNet/terraform-provider-intersight/blob/db33ed7251225a87007ab967f213f8f8e76df22f/intersight/data_source_intersight_fabric_switch_control_policy.go#L291

https://github.com/CiscoDevNet/terraform-provider-intersight/blob/db33ed7251225a87007ab967f213f8f8e76df22f/intersight/resource_intersight_fabric_switch_control_policy.go#L369

**Comment by scotttyso** [comment]
@vvb and @heitmanr - with this resolved in 1.0.36 shouldn't this be closed.
