### ISSUE TITLE
[Question] Provisioners support resource `intersight_virtualization_virtual_machine`

### ISSUE THREAD

**Issue by jgomezve** [CiscoDevNet/terraform-provider-intersight#248]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal configuration to reproduce the issue?
- [ ] Have you [tested with the latest master] to confirm the issue still exists?
- [ ] Have you provided the terraform console logs with environment variable set to TF_LOG=trace?

##### Description

Does the resource `intersight_virtualization_virtual_machine` support remote and local provisioners?

**Comment by scotttyso** [comment]
@jgomezve - the resource in question above only provides operational actions for a virtual machine.  Meaning you can power and power it off.  It is not a provisioner.

Not really sure it is a great resource for Terraform.  I think this would probably be a better use case for Ansible.

**Comment by the-akhil-nair** [comment]
@jgomezve I hope we answered your queries. If you have any doubts in future please create a new issue with similar tag or please feel free to re-open this issue. Closing this issue for now.
