### ISSUE TITLE
[ISSUE] Post Deployment Actions fail with 500 Internal Server Error

### ISSUE THREAD

**Issue by egrosdou** [CiscoDevNet/terraform-provider-intersight#258]
#### Bug Report Checklist

- [x] Have you provided a full/minimal configuration to reproduce the issue?
- [x] Have you [tested with the latest master] to confirm the issue still exists?
- [x] Have you provided the terraform console logs with environment variable set to TF_LOG=trace?

##### Description

While working with the resource "intersight_workflow_catalog_service_request", noticed that a post deployment action fails with a 500 server error. The error can be found below.

```bash
│ Error: error occurred while creating WorkflowCatalogServiceRequest: 500 Internal Server Error Response from endpoint: {"code":"InvalidRequest","message":"Failed to get service item instance object.","messageId":"Workflow_ServiceItemInstanceGetFailed","traceId":"P0N8A0EemIhI3fNdZvGf3_evRI6P_7wIlnPZAeaAD_WOsGv6HuwKPQ=="}
│ 
│   with intersight_workflow_catalog_service_request.scale_request,
│   on main.tf line 53, in resource "intersight_workflow_catalog_service_request" "scale_request":
│   53: resource "intersight_workflow_catalog_service_request" "scale_request" { 
```
To ensure this is not a general issue with the Service Catalog items or the cloud version, I perform the same action with the REST API. The Rest API execution succeeds.

REST API Request: https://intersight.com/api/v1/workflow/CatalogServiceRequests

Body:
```json
{
  "ClassId": "workflow.CatalogServiceRequest",
  "ObjectType": "workflow.CatalogServiceRequest",
  "Input": {
    "RKE2Cluster": {
        "ControllerCount": 1,
        "WorkerCount": 1
    }
  },
  "Label": "",
  "Name": "test-tf-cluster-05",
  "Operation": 
  {
    "ClassId": "workflow.OperationTypePostDeployment",
    "ObjectType": "workflow.OperationTypePostDeployment",
    "OperationType": "PostDeployment",
    "ServiceItemActionDefinition": {
        "ObjectType": "workflow.ServiceItemActionDefinition",
        "ClassId": "cmrf.CmRf",
        "Moid": "65689a896e75733101ee6258"
    },
    "ServiceItemInstance": {
        "ObjectType": "workflow.ServiceItemInstance",
        "ClassId": "cmrf.CmRf",
        "Moid": "65705e5d6e7573310117c595"
    }
},
  "Status": "NotCreated",
  "CatalogItemDefinition": {
    "ObjectType": "workflow.CatalogItemDefinition",
    "ClassId": "mo.MoRef",
    "Moid": "6566121a6e75733101e215ce",
    "link": "https://www.intersight.com/api/v1/workflow/CatalogItemDefinitions/6566121a6e75733101e215ce"
}}
```

For testing purposes, the Moids in the body request need to get updated with relevant ones.

##### Terraform-provider-intersight version

v1.0.42

##### Configuration file

``` hcl
# Create a new resource as a Post Deploy action to scale the existing cluster
resource "intersight_workflow_catalog_service_request" "scale_request" {
  name        = "${var.request_name}_${var.ClusterID}"
  object_type = "workflow.CatalogServiceRequest"
  class_id    = "workflow.CatalogServiceRequest"

  catalog_item_definition = [
    {
      additional_properties = ""
      selector              = ""
      class_id              = "mo.MoRef"
      moid                  = var.moid
      object_type           = "workflow.CatalogItemDefinition"
    }
  ]

  operation = [
    {
      additional_properties = ""
      class_id              = "workflow.OperationTypePostDeployment"
      object_type           = "workflow.OperationTypePostDeployment"
      operation_type        = "PostDeployment"

      service_item_action_definition = {
        object_type = "workflow.ServiceItemActionDefinition"
        class_id    = "cmrf.CmRf"
        moid = "mymoid"
      }

      service_item_instance = {
        object_type = "workflow.ServiceItemInstance"
        class_id    = "cmrf.CmRf"
        moid = local.filtered_results[length(local.filtered_results) - 1].service_item_instance[0].moid
      }
    }
  ]

  description = var.description

  input = jsonencode(
    {
      "RKE2Cluster" : {
        "ControllerCount" : var.ScaleControllerCount,
        "WorkerCount" : var.ScaleWorkerCount
      }
    }
  )
}
```

##### Actual output (Attach screenshots if applicable)

```bash
│ Error: error occurred while creating WorkflowCatalogServiceRequest: 500 Internal Server Error Response from endpoint: {"code":"InvalidRequest","message":"Failed to get service item instance object.","messageId":"Workflow_ServiceItemInstanceGetFailed","traceId":"P0N8A0EemIhI3fNdZvGf3_evRI6P_7wIlnPZAeaAD_WOsGv6HuwKPQ=="}
│ 
│   with intersight_workflow_catalog_service_request.scale_request,
│   on main.tf line 53, in resource "intersight_workflow_catalog_service_request" "scale_request":
│   53: resource "intersight_workflow_catalog_service_request" "scale_request" { 
```

**Comment by vvb** [comment]
Based on the error from Intersight, I assume you have an issue with `moid = local.filtered_results[length(local.filtered_results) - 1].service_item_instance[0].moid`

Please turn on trace logging use `export TF_LOG=trace` and then do `terraform apply`. Somewhere in the console output you will see the actual JSON payload that terraform is sending to Intersight. Please validate that the right Moid is being set for the ServiceItemInstance

**Comment by egrosdou01** [comment]
Hi, find the trace log file attached. I replaced the MOID with a string value from the POST REST call and I still get the same error. Also, can you advice what is the best way to grab the service_item_instance MOID?

REST CALL

```
{
  "ClassId": "workflow.CatalogServiceRequest",
  "ObjectType": "workflow.CatalogServiceRequest",
  "Input": {
    "RKE2Cluster": {
        "ControllerCount": 1,
        "WorkerCount": 1
    }
  },
  "Label": "",
  "Name": "test_eleni-tf-cluster-01",
  "Operation": 
  {
    "ClassId": "workflow.OperationTypePostDeployment",
    "ObjectType": "workflow.OperationTypePostDeployment",
    "OperationType": "PostDeployment",
    "ServiceItemActionDefinition": {
        "ObjectType": "workflow.ServiceItemActionDefinition",
        "ClassId": "cmrf.CmRf",
        "Moid": "65689a896e75733101ee6258"
    },
    "ServiceItemInstance": {
        "ObjectType": "workflow.ServiceItemInstance",
        "ClassId": "cmrf.CmRf",
        "Moid": "6581e85b6e757331016b5043"
    }
},
  "Status": "NotCreated",
  "CatalogItemDefinition": {
    "ObjectType": "workflow.CatalogItemDefinition",
    "ClassId": "mo.MoRef",
    "Moid": "6566121a6e75733101e215ce",
    "link": "https://www.intersight.com/api/v1/workflow/CatalogItemDefinitions/6566121a6e75733101e215ce"
}

}
```
Terraform Apply

<img width="1442" alt="Screenshot 2023-12-19 at 20 32 19" src="https://github.com/CiscoDevNet/terraform-provider-intersight/assets/147995681/1a470655-6ce7-42f6-805e-aa44bf5a94a1">


<img width="1109" alt="Screenshot 2023-12-19 at 20 23 13" src="https://github.com/CiscoDevNet/terraform-provider-intersight/assets/147995681/4af3850a-32d9-471e-84ca-e5f7b86f69f0">
[terraform.log](https://github.com/CiscoDevNet/terraform-provider-intersight/files/13719567/terraform.log)

**Comment by vvb** [comment]
At first glance the request seems correct to me. There are a few things that might still produce the error you are seeing. Please check the below,
1. Is the API key and secret being used created on the same account/user where apidocs query worked for you.
2. Is the API key and secret using the same Role that they user for which apidocs query worked.

**Comment by egrosdou01** [comment]
I can confirm that both keys are created under the same account and Role. The only difference is that the API key for the REST calls is for purpose "Intersight SDK" while the one for Terraform is for "Legacy Python SDK".

**Comment by egrosdou** [comment]
Any updates @vvb? Did you have a chance to look at the logs provided or any recommendations to avoid the 500 error? Thanks in advance.

**Comment by prmedipa** [comment]
@egrosdou01 ServiceItemInstance doesnt exist. Could you please create new one and check.

get  /api/v1/workflow/ServiceItemInstances/6581e85b6e757331016b5043
Error: 
{
  "code": "NotFound",
  "message": "Cannot execute the request. The request object '6581e85b6e757331016b5043' does not exist.",
  "messageId": "barcelona_request_object_does_not_exist",
  "messageParams": {
    "1": "6581e85b6e757331016b5043"
  },
  "traceId": "VsSKNLs3aQDpu2aQeHuzA50OHTiUGeeoh7P9VGBNg0GJj9mQSc-MEw=="
}

**Comment by egrosdou01** [comment]
@prmedipa As the ticket is 7 months old, I would not expect the MOIDs defined here are valid. I shared with new information with you. Thanks.

**Comment by egrosdou01** [comment]
After trying the latest TF provider (1.0.50), the issue is still the same.

**Comment by vvb** [comment]
@egrosdou01 - One issue we found based on the API payload you shared with @prmedipa is that the ServiceItemActionDefinition MO being used in the CatalogServiceRequest is not correct.  The Overall operation was post deployment, but the ServiceItemActionDefinition was of a Deployment operation. Intersight backend is lacking some validations to make this easy for debugging. I have provided feedback to the backend team on this.

For a PostDoyment CatalogServiceRequest you should be using ServiceItemDefinitions that are one of `ActionProperties.OperationType eq 'PostDeployment' and ServiceItemDefinition.Moid eq  <ServiceItemInstances->ServiceItemDefinition.Moid>'`

**Comment by prmedipa** [comment]
@egrosdou01 One issue we found based on terraform file. We have to include "ServiceItemInstance" and "ServiceItemActionDefinition" in additional_properties.

# Create a new resource as a Post Deploy action to scale the existing cluster
resource "intersight_workflow_catalog_service_request" "scale_request" {
  name        = "${var.request_name}_${var.ClusterID}"
  object_type = "workflow.CatalogServiceRequest"
  class_id    = "workflow.CatalogServiceRequest"

  catalog_item_definition = [
    {
      additional_properties = ""
      selector              = ""
      class_id              = "mo.MoRef"
      moid                  = var.moid
      object_type           = "workflow.CatalogItemDefinition"
    }
  ]

  operation = [
    {

      class_id              = "workflow.OperationTypePostDeployment"
      object_type           = "workflow.OperationTypePostDeployment"
      operation_type        = "PostDeployment"

      **additional_properties = jsonencode({
      ServiceItemInstance = {
        ObjectType = "workflow.ServiceItemInstance"
        ClassId    = "cmrf.CmRf"
        Moid = var.ServiceItemInstanceMoid
      },
      ServiceItemActionDefinition = {
        ObjectType = "workflow.ServiceItemActionDefinition"
        ClassId    = "cmrf.CmRf"
        Moid =  var.ServiceItemActionDefinitionMoid
      }})**
    }
  ]

  description = var.description

  input = jsonencode(
    {
      "RKE2Cluster" : {
        "ControllerCount" : var.ScaleControllerCount,
        "WorkerCount" : var.ScaleWorkerCount
      }
    }
  )
}

**Comment by prmedipa** [comment]
The following terraform configuration file will identify right "ServiceItemInstance"  and "ServiceItemActionDefinition" and trigger post deployment. You can change the OperationType as PostDeployment or Deployment to align with your requirements. If you want to get the KubeConfig change the label accordingly.

```
data "intersight_workflow_catalog_service_request" "cat_sr" {
  moid = var.moid
}

data "intersight_workflow_service_item_action_instance" "svc_item" {
  moid = data.intersight_workflow_catalog_service_request.cat_sr.results[0].service_item_action_instances[0].moid
}

data "intersight_workflow_service_item_action_definition" "svc_item_act_def" {
  label = "Scale Cluster Workers"
  additional_properties = jsonencode({
    ActionProperties = {
      OperationType = "PostDeployment"
    }
    ServiceItemDefinition = {
      Moid = data.intersight_workflow_service_item_action_instance.svc_item.results[0].service_item_definition[0].moid
    }
  })
}

resource "intersight_workflow_catalog_service_request" "scale_request" {
  name        = "akhinair_test"
  object_type = "workflow.CatalogServiceRequest"
  class_id    = "workflow.CatalogServiceRequest"
  catalog_item_definition = [
    {
      additional_properties = ""
      selector              = ""
      class_id              = "mo.MoRef"
      moid                  = data.intersight_workflow_catalog_service_request.cat_sr.results.0.catalog_item_definition.0.moid
      object_type           = "workflow.CatalogItemDefinition"
    }
  ]
  operation = [
    {
      class_id              = "workflow.OperationTypePostDeployment"
      object_type           = "workflow.OperationTypePostDeployment"
      operation_type        = "PostDeployment"
      additional_properties = jsonencode({
      ServiceItemInstance = {
        ObjectType = "workflow.ServiceItemInstance"
        ClassId    = "cmrf.CmRf"
        Moid = data.intersight_workflow_catalog_service_request.cat_sr.results.0.service_item_instances.0.moid
      },
      ServiceItemActionDefinition = {
        ObjectType = "workflow.ServiceItemActionDefinition"
        ClassId    = "cmrf.CmRf"
        Moid =  data.intersight_workflow_service_item_action_definition.svc_item_act_def.id
      }})
    }
  ]
  description = "post deployment"
  input = jsonencode(
    {
      "OpenShiftClusterVSphere" : {
        "WorkerCount" : 4
      }
    }
  )
}

**Comment by egrosdou01** [comment]
Important Notes
- Ensure the **latest** Intersight Terraform Provider is used (tested with v1.0.56)
- Enable **sleep** conditions to ensure the Post Deployment actions are available after the Service Catalog Item has been requested. The timer depends on what it is deployed.

Example - data.tf structure
```
data "intersight_workflow_catalog_service_request" "cat_sr" {
  depends_on = [time_sleep.wait]
  moid       = intersight_workflow_catalog_service_request.catalogue_request.id
}

data "intersight_workflow_service_item_action_instance" "svc_item" {
  moid = data.intersight_workflow_catalog_service_request.cat_sr.results[0].service_item_action_instances[0].moid
}

data "intersight_workflow_service_item_action_definition" "svc_item_act_def_scale" {
  depends_on = [time_sleep.wait]
  label      = "Scale"
  additional_properties = jsonencode({
    ActionProperties = {
      OperationType = "PostDeployment"
    }
    ServiceItemDefinition = {
      Moid = data.intersight_workflow_service_item_action_instance.svc_item.results[0].service_item_definition[0].moid
    }
  })
}
```

Example - main.tf

```
resource "intersight_workflow_catalog_service_request" "scale_request" {
  depends_on  = [time_sleep.wait]
  name        = "scale"
  object_type = "workflow.CatalogServiceRequest"
  class_id    = "workflow.CatalogServiceRequest"
  catalog_item_definition = [
    {
      additional_properties = ""
      selector              = ""
      class_id              = "mo.MoRef"
      moid                  = data.intersight_workflow_catalog_service_request.cat_sr.results.0.catalog_item_definition.0.moid
      object_type           = "workflow.CatalogItemDefinition"
    }
  ]
  operation = [
    {
      class_id       = "workflow.OperationTypePostDeployment"
      object_type    = "workflow.OperationTypePostDeployment"
      operation_type = "PostDeployment"
      additional_properties = jsonencode({
        ServiceItemInstance = {
          ObjectType = "workflow.ServiceItemInstance"
          Moid       = data.intersight_workflow_catalog_service_request.cat_sr.results.0.service_item_instances.0.moid
        },
        ServiceItemActionDefinition = {
          ObjectType = "workflow.ServiceItemActionDefinition"
          Moid       = data.intersight_workflow_service_item_action_definition.svc_item_act_def_scale.id
      } })
    }
  ]
  description = "post deployment"
  input = jsonencode(
    {
      "SERVICE OFFERING NAME" : {
        "EXPECTED VARIABLES FOR API CALL" : "YOUR VALUE"
      }
    }
  )
}
```

**Comment by egrosdou** [comment]
The issue has been resolved.
