### ISSUE TITLE
[ISSUE] Unsetting src_template does not remove setting template association

### ISSUE THREAD

**Issue by rmtilson** [CiscoDevNet/terraform-provider-intersight#261]
#### Bug Report Checklist

- [x] Have you provided a full/minimal configuration to reproduce the issue?
- [x] Have you [tested with the latest master] to confirm the issue still exists?
- [ ] Have you provided the terraform console logs with environment variable set to TF_LOG=trace?

##### Description

Setting the src_template = [] works. The plan correctly show the remove of the attached profile. 

The apply successfully executes the change but template is not unassociated Intersight. 

Trying to work out the process to unassociate a template to a profile. Then run a merge on the new template then associate to the new template. 

Looking at the api when unassigning via Intersight the request is {"SrcTemplate":null}. Deleting the block does not do anything. Using the attribute as block atleast got terraform properly plan on removing the template association. 
 

##### Terraform-provider-intersight version

1.0.44

##### Actual output (Attach screenshots if applicable)

 # intersight_server_profile.server_profile["pwd1n2"] will be updated in-place
  ~ resource "intersight_server_profile" "server_profile" {
        id                                    = "659f70e977696e330180e5f1"
        name                                  = "pwd1n2"
      ~ src_template                          = [
          - {
              - additional_properties = ""
              - class_id              = "mo.MoRef"
              - moid                  = "6573d55177696e33017d485c"
              - object_type           = "server.ProfileTemplate"
              - selector              = ""
            },
        ]
        tags                                  = []
        # (45 unchanged attributes hidden)
    }

  # intersight_server_profile.server_profile["pwd2n1"] will be updated in-place
  ~ resource "intersight_server_profile" "server_profile" {
        id                                    = "659f70e977696e330180e5c9"
        name                                  = "pwd2n1"
      ~ src_template                          = [
          - {
              - additional_properties = ""
              - class_id              = "mo.MoRef"
              - moid                  = "6573d55177696e33017d485c"
              - object_type           = "server.ProfileTemplate"
              - selector              = ""
            },
        ]
        tags                                  = []
        # (45 unchanged attributes hidden)
    }

intersight_server_profile.server_profile["pwd2n1"]: Modifying... [id=659f70e977696e330180e5c9]
intersight_server_profile.server_profile["pwd1n2"]: Modifying... [id=659f70e977696e330180e5f1]
intersight_server_profile.server_profile["pwd1n2"]: Modifications complete after 1s [id=659f70e977696e330180e5f1]
intersight_server_profile.server_profile["pwd2n1"]: Modifications complete after 1s [id=659f70e977696e330180e5c9]

**Comment by scotttyso** [comment]
@rmtilson I answered this in the QUESTION you had as well.  But this isn't an issue with the provider.  This is how the API works.

the change to the template requires the bulk_mo_merger to be updated, and this is the way I am accomplishing it today. 
https://github.com/terraform-cisco-modules/easy-imm/tree/main/update_server_template

The biggest challenge is that the bulk_mo_merger is ephimeral so Terraform cannot track changes made to it.  Same with all the bulk api resources.

**Comment by rmtilson** [comment]
@scotttyso Yes, on the bulk_mo_merger to actually do the updating of the policies if a profile needs to be changed to match a different template or updating on policy change. 

The src_template is needed to reflect the proper "linked" template in the gui. Simply updating the moid value returns a 403 error that the profiles is already associated to a template from my testing.

I am more than happy to discuss on call, maybe my work flow is wrong or I am not understanding something right.

I change the template referenced the mo_merger is triggered but fails on the updating of the src_template value.
----------------------------------------------------------------------------------------

Terraform will perform the following actions:

  # intersight_bulk_mo_merger.merge["pwd2n1"] will be created
  + resource "intersight_bulk_mo_merger" "merge" {
      + account_moid         = (known after apply)
      + ancestors            = (known after apply)
      + class_id             = "bulk.MoMerger"
      + create_time          = (known after apply)
      + domain_group_moid    = (known after apply)
      + id                   = (known after apply)
      + merge_action         = "Replace"
      + mod_time             = (known after apply)
      + moid                 = (known after apply)
      + object_type          = "bulk.MoMerger"
      + organization         = (known after apply)
      + owners               = (known after apply)
      + parent               = (known after apply)
      + permission_resources = (known after apply)
      + responses            = (known after apply)
      + shared_scope         = (known after apply)
      + sources              = [
          + {
              + account_moid         = (known after apply)
              + ancestors            = (known after apply)
              + class_id             = (known after apply)
              + create_time          = (known after apply)
              + domain_group_moid    = (known after apply)
              + mod_time             = (known after apply)
              + moid                 = "6573d55177696e33017d485c"
              + object_type          = "server.ProfileTemplate"
              + owners               = (known after apply)
              + parent               = (known after apply)
              + permission_resources = (known after apply)
              + shared_scope         = (known after apply)
              + tags                 = (known after apply)
              + version_context      = (known after apply)
            },
        ]
      + tags                 = (known after apply)
      + target_config        = (known after apply)
      + targets              = [
          + {
              + account_moid         = (known after apply)
              + ancestors            = (known after apply)
              + class_id             = (known after apply)
              + create_time          = (known after apply)
              + domain_group_moid    = (known after apply)
              + mod_time             = (known after apply)
              + moid                 = "659f70e977696e330180e5c9"
              + object_type          = "server.Profile"
              + owners               = (known after apply)
              + parent               = (known after apply)
              + permission_resources = (known after apply)
              + shared_scope         = (known after apply)
              + tags                 = (known after apply)
              + version_context      = (known after apply)
            },
        ]
      + version_context      = (known after apply)
    }

  # intersight_server_profile.server_profile["pwd2n1"] will be updated in-place
  ~ resource "intersight_server_profile" "server_profile" {
        id                                    = "659f70e977696e330180e5c9"
        name                                  = "pwd2n1"
      ~ src_template                          = [
          ~ {
              ~ moid                  = "6573d8c577696e33017d70e8" -> "6573d55177696e33017d485c"
                # (4 unchanged attributes hidden)
            },
        ]
        tags                                  = []
        # (45 unchanged attributes hidden)
    }

Plan: 1 to add, 1 to change, 0 to destroy.
intersight_server_profile.server_profile["pwd2n1"]: Modifying... [id=659f70e977696e330180e5c9]
╷
│ Error: error occurred while updating ServerProfile: 403 Forbidden Response from endpoint: {"code":"InvalidRequest","message":"Server profile already attached to a profile template. Cannot apply changes from other sources.","messageId":"gershwin_derived_sp_invalid_src","traceId":"cpXVm1KRWEbUHnFXcgb87wk-ZFYOiDr66hjoJX161H6WKw_A1a0D_Q=="}
│
│   with intersight_server_profile.server_profile["pwd2n1"],
│   on serivce_profiles.tf line 85, in resource "intersight_server_profile" "server_profile":
│   85: resource "intersight_server_profile" "server_profile" {
│
╵

**Comment by scotttyso** [comment]
@rmtilson  https://github.com/CiscoDevNet/terraform-provider-intersight/issues/263

**Comment by scotttyso** [comment]
@rmtilson 

Based on the recommendation of a colleague I tested again today using additional_properties for the source template and I can attach detach by using this method.

Now I do have to run a plan and apply two times, to detach a template, but it is working now.

Below is my yaml file that I am using with the easy-imm module.  To detach the template I set `detach_template` eq `true`.  then commenting that out or setting it back to `false`, will attach the new template on the next run.  This works with the bulk_merge set to ignore all changes as well.

Example below
```
---
#======================================
#   Profiles -> Server - Variables
#======================================
Asgard:
  profiles:
    server:
      - action: No-op
        attach_template: true
        #detach_template: true
        domain_name: example-ucs
        target_platform: FIAttached
        targets:
          - name: r143e-2-6
            pre_assign:
              chassis_id: 2
              slot_id: 6
        ucs_server_profile_template: common/aci-M5-intel-virtual-M2-pxe
```

If this answers your question please close out this issue.

**Comment by scotttyso** [comment]
As for the resource additional properties I am doing the following
```
  additional_properties = jsonencode({
    SrcTemplate = length(regexall("UNUSED", each.value.ucs_server_profile_template)) == 0 && each.value.detach_template == false ? {
      Moid       = local.server_templates[each.value.ucs_server_profile_template].moid
      ObjectType = "server.ProfileTemplate"
    } : null
  })
```

**Comment by rmtilson** [comment]
Yes, is a suitable workaround. I have been exploring using ansible for deriving the profiles from templates. 

Thank you for looking into this and posting back.
