### ISSUE TITLE
[ISSUE] intersight_fabric_system_qos_policy - classes - bandwidth

### ISSUE THREAD

**Issue by scotttyso** [CiscoDevNet/terraform-provider-intersight#262]
#### Bug Report Checklist

- [x] Have you provided a full/minimal configuration to reproduce the issue?
- [x] Have you [tested with the latest master] to confirm the issue still exists?
- [x] Have you provided the terraform console logs with environment variable set to TF_LOG=trace?

##### Description

Please make the bandwidth_percent a hidden/ignored field in the Terraform Provider for this resource in the classes fields
##### Terraform-provider-intersight version

<=1.0.44
##### Actual output (Attach screenshots if applicable)

The problem is that Intersight calculates the bandwidth_percent, so there is no way to define in Terraform the value and get the Intersight API to accept the value.  This should not be a configurable field.

##### Suggest a fix
Instead of removing the attribute causing a backward compatibility issue, just have the provider ignore the input and accept what Intersight sets the value to.

The calculation for this value in the API is somehow different than what terraform will calculate using math, and they never agree.

**Comment by mohamuni** [comment]
Hi @scotttyso 
The `bandwidth_percent` field is supressed for difference, On subsequent applies difference for bandwidth_percent is ignored in subsequent applies. Can you please check this with latest intersight  terraform provider version.

**Comment by scotttyso** [comment]
@mohamuni - I am still seeing it come back with changes after updating to v1.0.56

```hcl
  # module.policies["map"].intersight_fabric_system_qos_policy.map["common/qos"] will be updated in-place
  ~ resource "intersight_fabric_system_qos_policy" "map" {
      ~ classes               = [
            # (4 unchanged elements hidden)
            {
                additional_properties = null
                admin_state           = "Enabled"
                bandwidth_percent     = 20
                class_id              = "fabric.QosClass"
                cos                   = 5
                mtu                   = 9216
                multicast_optimize    = false
                name                  = "Platinum"
                object_type           = "fabric.QosClass"
                packet_drop           = false
                weight                = 10
            },
          ~ {
              ~ bandwidth_percent     = 18 -> 16
                name                  = "Silver"
                # (9 unchanged attributes hidden)
            },
        ]
        id                    = "65d3788d6f62693001efccf3"
        name                  = "qos"
        tags                  = [
            {
                additional_properties = null
                key                   = "Module"
                value                 = "easy-imm"
            },
            {
                additional_properties = null
                key                   = "Version"
                value                 = "4.2.11-18533"
            },
        ]
        # (17 unchanged attributes hidden)
    }
```

**Comment by scotttyso** [comment]
This is working with v1.0.56
