### ISSUE TITLE
[ISSUE] Resource intersight_resourcepool_pool has insufficient parameters

### ISSUE THREAD

**Issue by cwilloughby-bw** [CiscoDevNet/terraform-provider-intersight#270]
#### Bug Report Checklist

- [x] Have you provided a full/minimal configuration to reproduce the issue?
- [x] Have you [tested with the latest master] to confirm the issue still exists?
- [x] Have you provided the terraform console logs with environment variable set to TF_LOG=trace?

##### Description

The `intersight_resourcepool_pool` resource does not support the full set of parameters required to create a "Server" type resource

##### Terraform-provider-intersight version

`1.0.47`

##### Configuration file

``` hcl
resource "intersight_resourcepool_pool" "hv-m5-g2" {
    name = "hypervisor-pool"

    resource_type = "Server"

    organization {
        object_type = "organization.Organization"
        moid = var.organization_id
    }
}
```

##### Actual output (Attach screenshots if applicable)

```
│ Error: error occurred while updating ResourcepoolPool: 400 Bad Request Response from endpoint: {"code":"InvalidRequest","message":"The Target Platform is mandatory for Resource Pool with Server type.","messageId":"malibu_res_poolparam_mandatory","traceId":"Xa-cW5SmZLetLdQFcmE9vMdeZUkOczYVcigJr5YczlmI_8o_GbJNbg=="}
│ 
│   with module.lab2-pod1.intersight_resourcepool_pool.hv-m5-g2,
│   on ../../modules/site_pod/pools_resource.tf line 14, in resource "intersight_resourcepool_pool" "hv-m5-g2":
│   14: resource "intersight_resourcepool_pool" "hv-m5-g2" {
```

##### Related issues/PRs

None found

##### Suggest a fix

Add support for Target Platform parameter to be set with the `intersight_resourcepool_pool` resource type.

**Comment by cwilloughby-bw** [comment]
Poking at the API, I'm not seeing an actual "Target Platform" parameter there either, so it seems that the presented error message is either inaccurate, or full data isn't being returned in GETs to the `/api/v1/resourcepool/Pools` endpoint

**Comment by vvb** [comment]
@cwilloughby-bw The error is poorly worded and not pointing to the exact property that is missing in the request. I will put in a request to update this error message to be more useful. I think you are missing `resource_pool_parameters`

resource_pool_parameters = {
  object_type = "resourcepool.ServerPoolParameters"
  management_mode = "Intersight"
}

**Comment by cwilloughby-bw** [comment]
Hey @vvb ,

Thanks for the prompt response! I saw that `resource_pool_parameters` property in the docs, but it only supports the `object_type` field. Attempting to set `management_mode` results in:

```
│ Error: Unsupported argument
│ 
│   on ../../modules/site_pod/pools_resource.tf line 26, in resource "intersight_resourcepool_pool" "hv-m5-g2":
│   26:         management_mode = "Intersight"
│ 
│ An argument named "management_mode" is not expected here.
```

**Comment by vvb** [comment]
We need to work on simplifying this. Below is what would work,

```
resource_pool_parameters {
  object_type    = "resourcepool.ServerPoolParameters"
  class_id       = "resourcepool.ServerPoolParameters"
  additional_properties = jsonencode({
    ResourcepoolServerPoolParameters = {
      ClassId = "resourcepool.ServerPoolParameters"
      ObjectType = "resourcepool.ServerPoolParameters"
      ManagementMode = "Intersight"
    }
  })
}
```

**Comment by cwilloughby-bw** [comment]
Hey @vvb,

This is not working properly in my testing. It's now creating the resource pool, but the management mode is always "IntersightStandalone". Subsequent plans show Terraform wanting to modify the management mode, but that never seems to actually happen.

Were you able to confirm that the above solution worked in your testing?

**Comment by scotttyso** [comment]
@cwilloughby-bw - See example here:
https://github.com/terraform-cisco-modules/terraform-intersight-pools/blob/main/resource.tf

**Comment by mohamuni** [comment]
Hi @cwilloughby-bw ,

Please find working example for creating resource pool and setting the ManagementMode attribute.

```
resource "intersight_resourcepool_pool" "demo_pool" {
    name = "DemoTfPool"
    resource_type = "Server"
    organization {
        object_type = "organization.Organization"
        moid = data.intersight_organization_organization.organization.id
    }
    resource_pool_parameters  {
            class_id = "resourcepool.ServerPoolParameters"
            object_type = "resourcepool.ServerPoolParameters"
            additional_properties = jsonencode({
                ManagementMode = "Intersight"
            })
    }
}
```

With respect to concerns regarding management mode is always "IntersightStandalone". Subsequent plans show Terraform wanting to modify the management mode, but that never seems to actually happen. We cannot change ManagementMode once the resource pool is created with particular ManagementMode. In case if you need to change ManagementMode you need to destroy the existing resource pool and create new resourcepool with the required ManagementMode. Please let us know in case of any issues/concerns

**Comment by the-akhil-nair** [comment]
Thanks @cwilloughby-bw  for reaching out to us.
I hope @mohamuni response will work for you.
Closing the issue now due to inactivity.
If you have any doubts or face any issue, you can re-open it again.
