### ISSUE TITLE
Many properties are hidden under the additional_property field.

### ISSUE THREAD

**Issue by baelen-git** [CiscoDevNet/terraform-provider-intersight#28]
Many resources or data sources in the Intersight Terraform Provider have properties which are hidden under the additional_properties property.

It is impossible to know which properties these are and Terraform can't do any validation on it.
Those properties sometimes are essential and need to be specified in the API spec under the root element, instead of under the additional_properties property.

There is a workaround when we inspect the payload through the GUI or when we query an existing policy to guess which properties need to be specified.
Then we can specify those properties using `jsonencode ({})` 

However this workaround is very user unfriendly and time consuming.

**Comment by code-lucidal58** [comment]
Resolved in version 1.0.0
