### ISSUE TITLE
The value of the "Optional" property is "True" everywhere

### ISSUE THREAD

**Issue by baelen-git** [CiscoDevNet/terraform-provider-intersight#29]
This creates many "internal error 500" messages when we try to create a resource that and 'forget' to specify and required field.

We have no way of knowing which properties are Optional and which ones are Required at the moment.

Please make sure that the Optional property is configured correctly for all resources.

**Comment by scotttyso** [comment]
@baelen-git - In recent provider versions this is solved.  I think this request should be closed.

**Comment by baelen-git** [comment]
thanks for verifying @scotttyso  I will close.
