### ISSUE TITLE
[ISSUE] Description - Receiving ERROR:  The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled on all intersight resources 

### ISSUE THREAD

**Issue by jvh-infra** [CiscoDevNet/terraform-provider-intersight#299]
#### Bug Report Checklist

- [ ] Have you provided a full/minimal configuration to reproduce the issue?
- [ ] Have you [tested with the latest master] to confirm the issue still exists?
- [ ] Have you provided the terraform console logs with environment variable set to TF_LOG=trace?

##### Description

Within the last week 15 days we are getting:  The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled.  on all of our intersight resources that already exist during any type of plan on TFE.      

##### Terraform-provider-intersight version

intersight = {
      source = "CiscoDevNet/intersight"
      version = "1.0.44"
    }

We have changed this to 1.0.55 which is the latest and that did not resolve the issue either.    

##### Configuration file

This is not a bug but an error that we are seeing and trying to figure out what to do about it.   Please help.    

##### Related issues/PRs

.   No there is not one reported for this.   

##### Suggest a fix

.    Maybe this is a timeout or number of resource issue.

**Comment by the-akhil-nair** [comment]
@jvh-infra Thanks for reaching out to us. 
Can you please share the terraform configuration where you are facing this error.
Also, can you please attach the stack trace if any which elaborate the actual issue so that we can analyse more on this issue.

**Comment by scotttyso** [comment]
@jvh-infra - might also want to check what terraform executable you are using.  In this discussion board, they fixed it with a terraform.exe upgrade.

https://discuss.hashicorp.com/t/the-plugin-grpcprovider-upgraderesourcestate-request-was-cancelled/37928/2

**Comment by jvh-infra** [comment]
Good Day.

Thank you so much for all of your help and assistance.      You can close this issue as well.

Thanks in advance.

James Van Horn



From: Tyson Scott ***@***.***>
Date: Friday, October 11, 2024 at 1:16 PM
To: CiscoDevNet/terraform-provider-intersight ***@***.***>
Cc: James Van Horn (Salt Lake City) ***@***.***>, Mention ***@***.***>
Subject: Re: [CiscoDevNet/terraform-provider-intersight] [ISSUE] Description - Receiving ERROR: The plugin.(*GRPCProvider).UpgradeResourceState request was cancelled on all intersight resources (Issue #299)

@jvh-infra<https://urldefense.com/v3/__https:/github.com/jvh-infra__;!!LZZzuBY!abW8wklIi5uq-bEXowLmr8GHqXKKIMflzK2c7gyJcbxDQF6nCLNzezi2M6pR4m-lEjQKLFL69Ip8NcVZT5PQdpskXvfL$> - might also want to check what terraform executable you are using. In this discussion board, they fixed it with a terraform.exe upgrade.

https://discuss.hashicorp.com/t/the-plugin-grpcprovider-upgraderesourcestate-request-was-cancelled/37928/2<https://urldefense.com/v3/__https:/discuss.hashicorp.com/t/the-plugin-grpcprovider-upgraderesourcestate-request-was-cancelled/37928/2__;!!LZZzuBY!abW8wklIi5uq-bEXowLmr8GHqXKKIMflzK2c7gyJcbxDQF6nCLNzezi2M6pR4m-lEjQKLFL69Ip8NcVZT5PQduWBPcI5$>

**Comment by the-akhil-nair** [comment]
Thanks for the confirmation @jvh-infra.
