### ISSUE TITLE
intersight_compute_physical_summary data source only works with Standalone servers

### ISSUE THREAD

**Issue by dsoper2** [CiscoDevNet/terraform-provider-intersight#3]
Following data source:

data "intersight_compute_physical_summary" "server_moid" {
  name  = var.server_list[count.index].name
  count = length(var.server_list)
}

Is resulting in a filtered search for Standalone servers and does not support other ManagementModes:

2020/11/04 13:22:04 client.go:392: 
2020-11-04T13:22:04.571-0600 [DEBUG] plugin.terraform-provider-intersight_v0.1.0: GET /api/v1/compute/PhysicalSummaries?%24filter=ManagementMode+eq+%27IntersightStandalone%27+and+Name+eq+%27IMM-6454-D23-1-1%27 HTTP/1.1

**Comment by vvb** [comment]
@dsoper2 thank you for reporting this issue. We will work on a fix.

**Comment by code-lucidal58** [comment]
Issue resolved in v0.1.1 tagged release.
