### ISSUE TITLE
 Kubernetes Node Group Policy get renamed by Intersight

### ISSUE THREAD

**Issue by baelen-git** [CiscoDevNet/terraform-provider-intersight#32]
When I create a Kubernetes Node Group Policy with the name "test-boris" and I use this in a profile.
After I deploy the profile this nodegrouppolicy will get renamed by the Intersight backend to something like "test-boris-e892bfe783n" 

The next time I run my 'tf apply' it tells me that the name has been changed and terraform will try to rename the nodegrouppolicy again.

**Comment by vvb** [comment]
This looks like a backend issue. If the backend renames the policy, there is not way for terraform client to know this unless, the customer manually changes the name in the tf configuration file.

**Comment by code-lucidal58** [comment]
The name remains the same as mentioned in the tf file. Please verify that you still facing this issue. If yes, please share the configuration you are using.

**Comment by baelen-git** [comment]
The problem is resolved, thanks!
