### ISSUE TITLE
When deploying a new IKS cluster from Terraform, tf destroy doesn't clean up the provisioned resources.

### ISSUE THREAD

**Issue by baelen-git** [CiscoDevNet/terraform-provider-intersight#38]
When we deploy a new IKS cluster from Terraform it will kick off a workflow.
This workflow will provision new VM's, that have IP leases.

Terraform is not aware of the vm's which are provisioned, and they don't become part of the terraform.state file.
This means we are deploying infrastructure with terraform that cannot be managed by terraform, this is not the concept of terraform.

You can notice this specifically when you do a 'tf destroy' on your iks cluster profile, it will just delete the cluster profile.
It won't clean up the VM's and IP Leases which have ben created.
This behaviour does not match the terraform concept and should be adjusted.

**Comment by baelen-git** [comment]
The PODs, Services and other Kubernetes artefacts are also not getting cleaned up in Intersight.

**Comment by code-lucidal58** [comment]
Please attach a sample tf to regenerate this issue.

**Comment by baelen-git** [comment]
Hi, this is the code I use to create a profile and deploy it.
You can also use my repo: https://github.com/baelen-git/terraform-iks

The problem is that the resources which are provisioned by the workflow are not imported by Terraform, thus also not deleted on a ```terraform destroy```.
With the AWS provider the instance also gets provisioned in the background, but it waits for the resource to be provisioned and then imports it into the state file.

```
resource "intersight_kubernetes_cluster_profile" "IKS-k8s-profile" {
    name = var.iks_cluster_name
    description = "This Kubernetes Cluster profile has been created via Terraform"
    management_config {
        object_type = "kubernetes.ClusterManagementConfig"
        load_balancer_count = var.load_balancer_count
        ssh_keys = var.ssh_keys
        ssh_user = var.ssh_user
    }
    action = "Deploy"

    #references
    addons {
        object_type = "kubernetes.AddonPolicy"
        moid = intersight_kubernetes_addon_policy.IKS-Dashboard.id
    }

    cluster_ip_pools {
        object_type = "ippool.Pool"
        moid = intersight_ippool_pool.IKS-ippool-amslab.id
    }

    container_runtime_config { 
        object_type = "kubernetes.ContainerRuntimePolicy"
        moid = intersight_kubernetes_container_runtime_policy.IKS-container-runtime_with_proxy.id
    }

    net_config {
        object_type = "kubernetes.NetworkPolicy"
        moid = intersight_kubernetes_network_policy.IKS-network-policy-cluster1.id
    }

    sys_config {
        object_type = "kubernetes.SysConfigPolicy"
        moid = intersight_kubernetes_sys_config_policy.IKS-Sys-Config-Default.id
    }

    tags { 
        key = "Managed_By"
        value = "Terraform"
    }
    organization {
        object_type = "organization.Organization"
        moid = data.intersight_organization_organization.org.id
    } 
}
```

**Comment by baelen-git** [comment]
another resource that gets created during the deployment is the 'Essential Addon Policy'.
We would also need to get information about this resource so we can import it in our state file.

**Comment by code-lucidal58** [comment]
Aws does not import any additional resources/objects. After you create an AWS instance, it receives all details in the same resource and stores in tfstate file. It is straightforward. Here the ask is to get details of the VM instances whose, I assume, details are not included in the kubeClusterProfile response(received after terraform apply). Hence, these are two different scenarios.
If the VMs cannot sustain without a profile, they should get deleted along with the profile (handled by the backend service). 
If they can sustain, is it always required to delete the VMs? Won't there be scenarios where you do not want to delete the VM, but just the profile and attach the existing VMs with a new profile?

**Comment by code-lucidal58** [comment]
While creating an AWS instance, you create a resource of ec2 instance, and all the details of the VM are returned in the response. Here, triggering a deployment is triggering the creation of VMs that are of a different object type. Hence I think the situations are not comparable. 
I am not sure how the Kubernetes package's CRUD works. Hence, I have few questions before I get started on the code changes. After triggering deployment, does the details of the VMs are included in the response payload? If no, how to find them? Won't there be scenarios where the user does not want to delete the VM, instead want to delete the profile only, and later assign those VMs to a different profile.

**Comment by code-lucidal58** [comment]
Cleaning of VMs (implicitly dependent objects) has to be carried out by the endpoint. Closing this issue as no further discussion is found.
