### ISSUE TITLE
intersight_vnic_eth_adapter_policy resource missing default config option 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#45]
The Intersight GUI interface has an option: "Ethernet Adapter Default Configuration *" select default configuration" which is used to choose the default adapter policy from cisco. 

The customer's who want to stick with the default policy provided by cisco, they don't have an option to choose the default policy using the tf provider as the option is missing. 

Resource link in question: 
https://registry.terraform.io/providers/CiscoDevNet/intersight/latest/docs/resources/vnic_eth_adapter_policy

**Comment by code-lucidal58** [comment]
When this issue is resolved, it will also be extended to "select default configuration" in Fibre Channel Adapter Policy.

**Comment by code-lucidal58** [comment]
This ask is beyond the scope of terraform provider's features. The default configurations are a UI feature. To replicate the behaviour, data sources can be used. And, the fetched data can then be used to assign the values to properties in the corresponding resource. Hence closing this issue.
