### ISSUE TITLE
terraform-provider-intersight/USERGUIDE.md missing info on new secretkey option for provider

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/terraform-provider-intersight#46]
Issue title says it all - unless user knew about the breaking change that forced a 1.0.0 version, there are no other docs available indicating that the secretkey option existed.

Please update the User Guide to reflect the new information.

Thanks!

**Comment by code-lucidal58** [comment]
The details of the breaking change was included in the release notes: https://github.com/CiscoDevNet/terraform-provider-intersight/releases/tag/v1.0.0
Thank you your suggestion. A ChangeLog.md will be added to reflect the changes in each version of the provider.

**Comment by code-lucidal58** [comment]
CHANGELOG.md added to the master branch. Hence, closing this issue
