### ISSUE TITLE
Resource: intersight_vnic_fc_adapter_policy missing select default fc adapter config option 

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#47]
The Intersight GUI interface has an option: "Fibre Channel Adapter Default Configuration *"  "select default configuration" which is used to choose the default adapter policy from cisco.

The customers who want to stick with the default policy provided by cisco, don't have an option to choose the default policy using the tf provider as the option is missing.

Resource link in question:
https://registry.terraform.io/providers/CiscoDevNet/intersight/latest/docs/resources/vnic_fc_adapter_policy

**Comment by code-lucidal58** [comment]
Similar issue #45 Both asks will be tracked under a single issue. Hence closing this thread.
