### ISSUE TITLE
Ability to claim device targets via intersight_asset_device_claims

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/terraform-provider-intersight#48]
asset/DeviceClaims exists in the Intersight OpenAPI so that users can claim a device via Device ID and Claim Code.  Specifically looking for this support in order to claim UCS C-series standalone.

Please expose this API via the Terraform provider.

Note: I see there is an intersight_asset_target resource which would seem to be a more generic approach to target claiming.  However, there is no information (or insufficient?  or broken links?) on how to provide the Device ID and Claim Code via that resource in order to successfully claim a device.

**Comment by sandkum5** [comment]
The device_claim resource doesn't seem to work. 

Getting the below error when I specify the device_id, claim_code. Tried adding other parameters but results in the same error. 

intersight_appliance_device_claim.appliance_device_claim: Creating...

Error: failed while creating ApplianceDeviceClaim: undefined response type Response from endpoint: {"code":"InvalidUrl","message":"Operation not supported. Check if the API path and method are valid.","messageId":"iam_invalid_method_operation","messageParams":{},"traceId":"xxxxx"}

**Comment by gve-vse-tim** [comment]
In the Intersight API Docs, the device_id and security_token are read only for appliance_device_claim.  Although, the Terraform Provider docs don't even list that resource as being available.

However, that's not the API endpoint (appliance/DeviceClaim) I'm referring to in this issue.  That's a different class/object in Intersight than the one I suggest exposing.

**Comment by the-akhil-nair** [comment]
@gve-vse-tim 

You can claim a particular target using the following configuration:

```hcl
resource "intersight_asset_device_claim" "target1" {
	security_token = "XXXXXXXXXXXX"
	serial_number = "XXXXXXXXXXX"
}
```
As you mentioned  intersight_asset_target resource can be used to perform the operation. Instead of the Device ID and Claim Code, we should use serial_number and security_token as parameters.

Please try the above configuration and let us know if you are still facing the issue.
