### ISSUE TITLE
Documentation missing Info

### ISSUE THREAD

**Issue by sandkum5** [CiscoDevNet/terraform-provider-intersight#5]
The documentation is missing the following feilds: 

-Example Usage   - This would be useful as we can start creating resource objects without first looking at the "POST" requests for each resource. 

-Attributes Reference 

-Import   - This would be useful when customers with existing resources are trying to get started with terraform. 

Got the following error when trying to use the import function: 
$ terraform import intersight_hyperflex_auto_support_policy.auto_support_policy xxxxxxxxx
intersight_hyperflex_auto_support_policy.auto_support_policy: Importing from ID "xxxxxxxxx"...
Error: resource intersight_hyperflex_auto_support_policy doesn't support import

Where I have tried using the ID as "id" or the "name" or the "moid". 

Same issue seen with other resources.

**Comment by code-lucidal58** [comment]
Usage examples will take a while to be added. Documentation for terraform import is added in 0.1.2
