### ISSUE TITLE
Resource intersight_iam_ldap_policy specifies incorrect required parameters

### ISSUE THREAD

**Issue by dchosnek** [CiscoDevNet/terraform-provider-intersight#51]
`intersight_iam_ldap_policy` will fail unless the following parameters are included in `base_properties`. I can set them to an empty string and the plan completes successfully. These should not be required parameters.

- `bind_dn` should not be required if `bind_method` is set to "LoginCredentials"
- `password` should not be required if `bind_method` is set to "LoginCredentials"
- `class_id` should not be required and is not listed as a parameter in the Terraform registry documentation
- `object_type` should not be required

**Comment by code-lucidal58** [comment]
Hi @dchosnek Are you still facing this issue? Please use the latest provider v1.0.8 and try? A point to note is the syntax for array elements will as shown below:
Suppose `arr` is an array of complex type. You can create two elements for this array as follows:
```
arr {
// element 1
}
arr {
//element 2
}
```

**Comment by dchosnek** [comment]
Sorry, @code-lucidal58 , I did just test this with 1.0.8 and all is well. Thanks for fixing.
