### ISSUE TITLE
intersight_networkconfig_policy examines IPv6 settings even when IPv6 disabled

### ISSUE THREAD

**Issue by dchosnek** [CiscoDevNet/terraform-provider-intersight#52]
Even with `enable_ipv6` set to `false`, each terraform plan/apply shows that there are changes to be applied:

```
alternate_ipv6dns_server = "::" -> null
preferred_ipv6dns_server = "::" -> null
```

I've tried setting those parameters initially to "::" to avoid this problem, but then the provider gives me an error stating those fields should not be set when IPv6 is disabled.

The provider should ignore these fields during plan/apply when IPv6 disabled.

**Comment by code-lucidal58** [comment]
Duplicate Issue. Please track #15 
Fix is under development
