### ISSUE TITLE
The property 'hyperflex.ClusterProfile:StorageType' does not exist.

### ISSUE THREAD

**Issue by jbrooks-sms** [CiscoDevNet/terraform-provider-intersight#56]
Receiving the following error when trying to create a profile.  I have set the storage_type = "HyperFlexDp" as well as commented out this to use the default which is showing "HyperFlexDp".  Using the version 1.0.1 provider, terraform 0.14.7, Hyperflex 4.0(2d) and Intersight 1.0.9-197 Private Virtual Appliance

Error: failed while creating HyperflexClusterProfile: 400 Bad Request Response from endpoint: {"code":"InvalidRequest","message":"Cannot create or modify the object ''. The property 'hyperflex.ClusterProfile:StorageType' does not exist.","messageId":"barcelona_request_property_does_not_exist","messageParams":{"1":"","2":"hyperflex.ClusterProfile","3":"StorageType"},"traceId":"NBd1050ced215dcfb867203ad6e1d2bce6"

resource "intersight_hyperflex_cluster_profile" "cluster_profile" {
  for_each = var.site_specifics
  name = each.value["cluster_name"]
  mgmt_platform = var.management_platform
//  storage_type = "HyperFlexDp"
  organization {
    object_type = "organization.Organization"
    moid        = intersight_organization_organization.org_data.moid
  }
  mgmt_ip_address = each.value["hx_mgmt_ip"]
  mac_address_prefix = each.value["mac_prefix"]
//  wwxn_prefix = var.wwxn_prefix
  storage_data_vlan {
    vlan_id = var.storage_vlan_id
  }
}

**Comment by code-lucidal58** [comment]
Looks like the provider was ahead of the appliance. Cross-verifying it over the production cloud, https://www.intersight.com/apidocs/apirefs/api/v1/hyperflex/ClusterProfiles/post/ , StorageType is a valid property. You may try by rerunning after updating the respective backend service. Closing this issue. You may reopen you if still face the issue.
