### ISSUE TITLE
intersight_syslog_policy resource documentation out of date - missing information on additional_properties

### ISSUE THREAD

**Issue by gve-vse-tim** [CiscoDevNet/terraform-provider-intersight#63]
The documentation shows the following semantics in the example (https://github.com/CiscoDevNet/terraform-provider-intersight/blob/master/examples/syslog/syslog_policy.md):

```
resource "intersight_syslog_policy" "syslog1" {
  name        = "syslog1"
  description = "demo syslog policy"
  local_clients {
    min_severity = "emergency"
    object_type  = "syslog.LocalFileLoggingClient"
  }
# <snip>
}

```
But these examples generate the following error:

```
Error: Incorrect attribute value type

  on general.tf line 202, in resource "intersight_syslog_policy" "syslog_local_only_notice":
 202:     local_clients = [ {
 203:       min_severity = "notice"
 204:       object_type = "syslog.LocalFileLoggingClient"
 205:     } ]

Inappropriate value for attribute "local_clients": element 0: attributes
"additional_properties" and "class_id" are required.

```

Visual Studio Code and its autocompletion suggest the following parameters:

```
    local_clients = [ {
      additional_properties = "value"
      class_id = "syslog.LocalFileLoggingClient"
      min_severity = "notice"
      object_type = "syslog.LocalFileLoggingClient"
    } ]

```

The object_type and class_id I can figure out from the API (create example class in GUI and GET the object via OpenAPI interface).  However, I have no idea what to put for the required additional_properties argument in the local_clients block.

Please update the example documentation - as well as the provider resource documentation as well - to indicate how to correctly define this resource.

Thanks!

**Comment by gve-vse-tim** [comment]
And, in playing around with values for the additional_properties argument, it seems like you can provide any string value you'd like but it never gets set in Intersight... thus, making the behavior non-idempotent.

```
  # intersight_syslog_policy.syslog_local_only_notice will be updated in-place
  ~ resource "intersight_syslog_policy" "syslog_local_only_notice" {
        id                    = "604547c56275722d30a29492"
      ~ local_clients         = [
          ~ {
              ~ additional_properties = "" -> "bob"
                # (3 unchanged elements hidden)
            },
        ]
        name                  = "syslog_local_only_notice"
        # (8 unchanged attributes hidden)
    }

```

So, why is additional_properties required but then forced to ""???

**Comment by baelen-git** [comment]
Hi Tim,

I believe this is a duplicate from -> https://github.com/CiscoDevNet/terraform-provider-intersight/issues/29
Can you confirm?

**Comment by gve-vse-tim** [comment]
Hey Boris,

Well, maybe - I read issue #29 as there are properties that are documented but they are all listed as "optional".  That is definitely a problem as you've stated in your issue.

In the above case, the documentation is simply wrong and there are attributes missing altogether in the docs and they ARE required.  Also, the example within the provider GitHub doesn't work either.

With all the revisions that are coming around, I should also start including the provider release as well.  I *think* these errors were with the 1.0.2 release.

**Comment by baelen-git** [comment]
I understand, you are actually missing some attributes in the docs, that is different.

**Comment by code-lucidal58** [comment]
HI @gve-vse-tim , using the exact same configuration as mentioned in [here](https://github.com/CiscoDevNet/terraform-provider-intersight/blob/master/examples/syslog/syslog_policy.md) is working fine. Tried with v1.0.7.

I see that you have made some syntax changes, like the addition of square brackets to array type properties. Please do not use that syntax. The correct HCL syntax for mentioning array of complex-type properties is 
```
disk {
    # element1
  }
  disk {
    # element2
  }
```
Regarding `additional_properties`, the documentations are updated to contain the information about where you need to include the property and where you don't have to. It also contains the details on what property-names are allowed in `additional_properties`. If this is missing from the documentation, you should refrain from using it. It exists to accommodate a situation where you want to test some new properties that are available in your setup but not in the production cloud.

**Comment by code-lucidal58** [comment]
Closing this thread as no there are on ongoing discussions.
