### ISSUE TITLE
data_source_intersight_kubernetes_cluster.go  "kube_config" [Backend: INTERSIGHT-10119]

### ISSUE THREAD

**Issue by vincentramirez** [CiscoDevNet/terraform-provider-intersight#64]
This datasource can currently output the kube_config as a raw blob, via TypeString here: https://github.com/CiscoDevNet/terraform-provider-intersight/blob/c40439eecf520ea8e267c7e0fdcdad586151dcba/intersight/data_source_intersight_kubernetes_cluster.go#L27

May I request this be enhanced to further parse the kube_config file to support Terraform outputs of specific parts of the kube_config file similar to the way that the azurerm Terraform Provider does this: https://github.com/terraform-providers/terraform-provider-azurerm/blob/7a8191d18c69c377f7681e23cb1ad3484ac6025e/azurerm/internal/services/containers/kubernetes_cluster_data_source.go#L333

In this provider the data source for kube_config uses `Type: schema.TypeList` and them breaks out the various sections of the kube_config file to include "host", "username", "client_certificate", etc..

Then there is a separate data_source called "kube_config_raw" that is used for TypeString blob output.  

The request here is to update the kube_config datasource to have two sources "kube_config" and "kube_config_raw".  "kube_config" should be a TypeList that parses the various parts of an IKS kube_config file: "server", "user", "client_certificate", "client_key", "cluster_ca", etc..

This will allow a user of the Intersight provider to create an IKS cluster then consume the outputs of the kube_config data to use with the Kubernetes or Helm Terraform provider similar to the below example:

```
provider "kubernetes" {
  host                   = azurerm_kubernetes_cluster.main.kube_config.0.host
  username               = azurerm_kubernetes_cluster.main.kube_config.0.username
  password               = azurerm_kubernetes_cluster.main.kube_config.0.password
  client_certificate     = base64decode(azurerm_kubernetes_cluster.main.kube_config.0.client_certificate)
  client_key             = base64decode(azurerm_kubernetes_cluster.main.kube_config.0.client_key)
  cluster_ca_certificate = base64decode(azurerm_kubernetes_cluster.main.kube_config.0.cluster_ca_certificate)
}
```

**Comment by code-lucidal58** [comment]
Thank you for the suggestion @vincentramirez The changes should start from the backend schema in Intersight. It will then be reflected in the terraform schema. This will also impact the API schemas for the respective models. I have forwarded this enhancement request to the concerned team. I will update this space when the feature is released.

**Comment by vvb** [comment]
Closing this as IKS has passed EoS Date. Refer - https://www.cisco.com/c/en/us/products/collateral/cloud-systems-management/intersight/ccp-iks-eol.html
