### ISSUE TITLE
Unable to create reusable IKS policies with Terraform

### ISSUE THREAD

**Issue by mkhaas** [CiscoDevNet/terraform-provider-intersight#66]
Currently it is possible to create reusable profiles but not reusable policies ;

**Comment by code-lucidal58** [comment]
Hi @mkhaas 
Please add the steps to reproduce the error.
The provider version you are trying this out it in. Please try to run with the latest one v1.0.7
These details will be required to help you fix the issue

**Comment by code-lucidal58** [comment]
Closing this thread as information is insufficient to fix the issue.
