### ISSUE TITLE
intersight_hyperflex_cluster_profile cannot set action without errors [Backend: INTERSIGHT-9991]

### ISSUE THREAD

**Issue by ucsarchitect** [CiscoDevNet/terraform-provider-intersight#67]
When trying to create a HyperFlex cluster profile and set the action to Validate or Deploy, so the cluster will start a validation or deployment task at the end, I get errors from the Intersight API. If I exclude the action it works perfectly but the cluster is in a no-op state and the validation or deployment must be manually triggered from within Intersight. 

Code:

        resource "intersight_hyperflex_cluster_profile" "cluster_profile" {
          name = var.cluster_name
          action = var.cluster_action
          organization {
            moid = var.intersight_organization_moid
          }
          mgmt_platform = var.management_platform
          replication = var.replication
          mgmt_ip_address = var.hx_mgmt_ip
          mac_address_prefix = var.mac_prefix
          wwxn_prefix = var.wwxn_prefix
          storage_data_vlan {
            name = var.storage_vlan_name
            vlan_id = var.storage_vlan_id
          }
        }

Response:

        module.cluster-profile.intersight_hyperflex_cluster_profile.cluster_profile: Creating...
        
        Error: failed while creating HyperflexClusterProfile: 500 Internal Server Error Response from endpoint: {"code":"InternalServerError","message":"Cannot execute the request due to an error. Retry later.","messageId":"barcelona_request_internal_error","messageParams":{},"traceId":"NB0004bb3231a33acb7d9b80443a864c48"}

**Comment by code-lucidal58** [comment]
Are you able to set "deploy" action in the second time apply?

**Comment by ucsarchitect** [comment]
I have not tried that, and even if it did work, I think that is the wrong approach to fix it. We should not need to apply a plan once to create the objects, then modify variables and run the plan again to get Intersight to trigger a job. For example, I assume that for a server profile the profile can be created and associated with a server all in one plan, and the job in Intersight would be triggered to perform the association. Creating an HX cluster profile should be just as easy.

**Comment by vvb** [comment]
This should be working right now. Can you confirm

**Comment by vvb** [comment]
Closing this based off my last comment. Please reopen if you still see this issue now.
