### ISSUE TITLE
data source documentation missing resource name

### ISSUE THREAD

**Issue by dchosnek** [CiscoDevNet/terraform-provider-intersight#69]
The documentation for data sources states that results can be obtained using the following format: `data.intersight_organization_organization.results[i].<propertyname>`. This is missing the **resource name** string and should look like `data.intersight_organization_organization.name.results[i].<propertyname>`.

I checked a handful of the data sources pages in the documentation, and they all had this error. Example: https://registry.terraform.io/providers/CiscoDevNet/intersight/latest/docs/data-sources/organization_organization

**Comment by code-lucidal58** [comment]
Thanks @dchosnek for pointing this out. It will be fixed in the upcoming release.

**Comment by code-lucidal58** [comment]
resolved with 1.0.7 release
