### ISSUE TITLE
object_type property is mandatory on Intersight backend side - TF provider should enforce object_type property presence

### ISSUE THREAD

**Issue by yannickcastano** [CiscoDevNet/terraform-provider-intersight#78]
According to the engineering team the Intersight backend requires object_type property to be associated to any object or sub-object. So far the Intersight REST API does not enforce this requirement, maybe the reason why the TF provider does not enforce in the same way. Python SDK on its side requires the presence of object_type parameter, thus generating error when reading or modifying objects created through Terraform (and with no object_type property manually defined)
I think this is important to be consistent and align the frontend requirements with the backend requirements, modifying the TF provider in order to auto-generate the object_type property could be easy and the object_type naming is consistent and linked to the ClassID

**Comment by yannickcastano** [comment]
So far it seems that only some sub-objects are impacted. For example on vnic/EthIfs, using below resource definition only creates object_type property for sub object vmqSettings (placement, cdn and usnic_settings sub objects have no object_type property or empty value when checking directly on the Intersight API)

resource "intersight_vnic_eth_if" "vnic_eth1_if_policy" {
  name = "eth1"
  order = 1
  placement {
    id       = var.adapter_slot_id
    pci_link = 0
    uplink   = 1
  }
  cdn {
    value = var.vnic_eth_if_cdn_nr_source
  }
  usnic_settings {
    cos      = 5 # int, Class of Service to be used for traffic on the usNIC.
    nr_count = 0 # int, Number of usNIC interfaces to be created.
  }
  vmq_settings {
    enabled             = var.vnic_eth_if_vmq_enabled
    multi_queue_support = false
    num_interrupts      = 1
    num_vmqs            = 1
  }
  lan_connectivity_policy {
    moid        = intersight_vnic_lan_connectivity_policy.vnic_lan_conn_policy.id
    object_type = "vnic.LanConnectivityPolicy"
  }
  eth_network_policy {
    moid = intersight_vnic_eth_network_policy.vnic_eth_network_policy.id
    object_type = "vnic.EthNetworkPolicy"
  }
  eth_adapter_policy {
    moid = intersight_vnic_eth_adapter_policy.vnic_eth_adapter_policy.id
    object_type = "vnic.EthAdapterPolicy"
  }
  eth_qos_policy {
    moid = intersight_vnic_eth_qos_policy.vnic_eth_qos_policy.id
    object_type = "vnic.EthQosPolicy"
  }
  depends_on = [intersight_vnic_lan_connectivity_policy.vnic_lan_conn_policy, intersight_vnic_eth_network_policy.vnic_eth_network_policy, intersight_vnic_eth_adapter_policy.vnic_eth_adapter_policy, intersight_vnic_eth_qos_policy.vnic_eth_qos_policy]
}

**Comment by vesposito** [comment]
And this is causing the following kind of errors to appear on the Intersight Python V3 SDK when trying to fetch all objects of a specific class that has sub-objects created without ObjectType attribute being set:
`Invalid inputs given to generate an instance of 'VnicEthIfListAllOf'. The input data was invalid for the allOf schema 'VnicEthIfListAllOf' in the composed schema 'VnicEthIfList'. Error=Invalid inputs given to generate an instance of 'VnicEthIfAllOf'. The input data was invalid for the allOf schema 'VnicEthIfAllOf' in the composed schema 'VnicEthIf'. Error=Invalid inputs given to generate an instance of 'MoBaseComplexType'. The input data was invalid for the allOf schema 'MoBaseComplexType' in the composed schema 'VnicUsnicSettings'. Error=Invalid value for `object_type` (), must be one of [long list of Mos]`

**Comment by code-lucidal58** [comment]
Fixed with 1.0.6 release
