### ISSUE TITLE
[BUG] Property "resource_pool" set to required

### ISSUE THREAD

**Issue by jcoday-cisco** [CiscoDevNet/terraform-provider-intersight#98]
**Describe the bug**
When defining the object type kubernetes.EsxiVirtualMachineInfraConfig, within the VmConfig block for object type kubernetes.VirtualMachineInfraConfigPolicy, the "resource_pool" key is not required to be set. However, in the Intersight API, there requires to be a value for that key, even if its an empty string. Without defining the "resource_pool" key, the terraform apply fails on the resource.

**To Reproduce**
1. Resource for intersight_kubernetes_virtual_machine_infra_config_policy
2. Add vm_config {} block to resource definition
3. Add additional_properties = jsonencode({}) block to vm_config block
4. define parameters "cluster", "datastore", "passphrase" in additional_properties
5. define rest of resource required parameters
4. Run `terraform plan' then 'terraform apply'
3. Create resource intersight_kubernetes_virtual_machine_infra_config_policy

**Expected behavior**
result should be a successful apply and creation of new resource with defined resource name

**Screenshots and Terraform configurations**
Terraform Configuration:
resource "intersight_kubernetes_virtual_machine_infra_config_policy" "vm_infra_config_policy" {
  name = "TFC-Test-1"
  description = "VM Infrastructure Config Policy used for Kubernetes deployment to vSphere"
  organization {
    object_type = "organization.Organization"
    moid = data.intersight_organization_organization.organization_moid.results[0].moid
  }
  target {
    moid = data.intersight_asset_device_registration.vcenter_device.results[0].moid
    object_type = "asset.DeviceRegistration"
  }
  vm_config {
    object_type = "kubernetes.EsxiVirtualMachineInfraConfig"
    interfaces = var.vsphere_portgroup
    additional_properties = jsonencode({
      cluster = var.vsphere_cluster
      datastore = var.vsphere_datastore
      passphrase = var.vsphere_password
    })
  }

**Provider Version :** v1.0.9

**Additional context**
After viewing the content sent from the terraform debug logs, I copied the payload being sent to Intersight and sent a POST request via the Intersight API page (https://intersight.com/apidocs/apirefs/api/v1/kubernetes/VirtualMachineInfraConfigPolicies/). This resulted in the same error as Terraform. I then added the {"ResourcePool": ""} key/value to the VmConfig{} block. After sending a POST request again, the request succeeded and the policy was created within Intersight. 

Working API call:
{
    "ClassId": "kubernetes.VirtualMachineInfraConfigPolicy",
    "Description": "VM Infrastructure Config Policy used for Kubernetes deployment to vSphere",
    "Name": "TFC-Test-1",
    "ObjectType": "kubernetes.VirtualMachineInfraConfigPolicy",
    "Organization": {
      "ClassId": "mo.MoRef",
      "Moid": "605b59056972652d319d8f64",
      "ObjectType": "organization.Organization",
      "Selector": ""
    },
    "Target": {
      "ClassId": "mo.MoRef",
      "Moid": "60c0cb2b6f72612d330ae9b5",
      "ObjectType": "asset.DeviceRegistration",
      "Selector": ""
    },
    "VmConfig": {
      "ClassId": "kubernetes.BaseVirtualMachineInfraConfig",
      "Interfaces": [
        "BACKBONE"
      ],
      "ObjectType": "kubernetes.EsxiVirtualMachineInfraConfig",
      "Cluster": "DC",
      "Datastore": "Infra_VMFS",
      "Passphrase": "Pizza!c30range",
      "ResourcePool": ""
    }
  }
[run-DC3vNZDQ1Sn4L7kn-apply-log.txt](https://github.com/CiscoDevNet/terraform-provider-intersight/files/6640831/run-DC3vNZDQ1Sn4L7kn-apply-log.txt)

**Comment by meghana-rajashekar** [comment]
@jcoday-cisco The jsonencode() block expects camel case for the key values. So, with that change, I'm able to create the resource with same configuration (without resource_pool) in the latest version 1.0.15

#### Please try changing the keys into camel case and try again with the latest version. Let us know if it still fails.


#### Below is the configuration I tried and it's output:

```hcl-terraform
resource "intersight_kubernetes_virtual_machine_infra_config_policy" "vm_infra_config_policy" {
  name        = "TFC-Test-1"
  description = "VM Infrastructure Config Policy used for Kubernetes deployment to vSphere"
  organization {
    object_type = "organization.Organization"
    moid        = data.intersight_organization_organization.default_org.results[0].moid
  }
  target {
    moid        = data.intersight_asset_device_registration.vcenter_device.results[0].moid
    object_type = "asset.DeviceRegistration"
  }
  vm_config {
    object_type = "kubernetes.EsxiVirtualMachineInfraConfig"
    interfaces = var.vsphere_portgroup
    additional_properties = jsonencode({
      Cluster    =  var.vsphere_cluster
      Datastore  = var.vsphere_datastore
      Passphrase =  var.vsphere_password
    })
  }
}
```

#### Upon terraform apply:

```bash
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # intersight_kubernetes_virtual_machine_infra_config_policy.vm_infra_config_policy will be created
  + resource "intersight_kubernetes_virtual_machine_infra_config_policy" "vm_infra_config_policy" {
      + account_moid         = (known after apply)
      + ancestors            = (known after apply)
      + class_id             = "kubernetes.VirtualMachineInfraConfigPolicy"
      + create_time          = (known after apply)
      + description          = "VM Infrastructure Config Policy used for Kubernetes deployment to vSphere"
      + domain_group_moid    = (known after apply)
      + id                   = (known after apply)
      + mod_time             = (known after apply)
      + moid                 = (known after apply)
      + name                 = "TFC-Test-1"
      + object_type          = "kubernetes.VirtualMachineInfraConfigPolicy"
      + organization         = [
          + {
              + additional_properties = null
              + class_id              = "mo.MoRef"
              + moid                  = "5daa09956972652d314fdac4"
              + object_type           = "organization.Organization"
              + selector              = null
            },
        ]
      + owners               = (known after apply)
      + parent               = (known after apply)
      + permission_resources = (known after apply)
      + profiles             = (known after apply)
      + shared_scope         = (known after apply)
      + tags                 = (known after apply)
      + target               = [
          + {
              + additional_properties = null
              + class_id              = "mo.MoRef"
              + moid                  = "610382026f72612d312b4a13"
              + object_type           = "asset.DeviceRegistration"
              + selector              = null
            },
        ]
      + version_context      = (known after apply)
      + vm_config            = [
          + {
              + additional_properties = jsonencode(
                    {
                      + Cluster    = "DC"
                      + Datastore  = "Infra_VMFS"
                      + Passphrase = "Pizza!c30range"
                    }
                )
              + class_id              = (known after apply)
              + interfaces            = [
                  + "BACKBONE",
                ]
              + object_type           = "kubernetes.EsxiVirtualMachineInfraConfig"
            },
        ]
    }

Plan: 1 to add, 0 to change, 0 to destroy.
intersight_kubernetes_virtual_machine_infra_config_policy.vm_infra_config_policy: Creating...
intersight_kubernetes_virtual_machine_infra_config_policy.vm_infra_config_policy: Creation complete after 3s [id=6138f7307a6f722d30e2d5de]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```
